name: Python Unit Tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Common:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs python v3.9
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      # Installs module dependencies
      - name: Install dependencies
        run: |
          cd Libs/Python/Common
          python -m pip install --upgrade pip
          pip install -r requirements.txt --find-links Libs/Python
      
      # Run module unit tests    
      - name: Run tests with unittest
        run: |
          cd Libs/Python/Common/tests
          python -m unittest discover
  
  FeedReader:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs python v3.9
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      # Install local libs
      - name: Install Local Libs
        run: |
           python -m pip install --upgrade pip
           python Tools/PythonLibs/build.py Libs/Python/Common/ Libs/Python/

      # Installs module dependencies
      - name: Install dependencies
        run: |
          cd FeedReader/
          pip install -r requirements.txt --find-links ./Libs/Python/
      
      # Run module unit tests    
      - name: Run tests with unittest
        run: |
          cd Feedreader/tests
          python -m unittest discover

  WordNet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs python v3.9
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      # Install local libs
      - name: Install Local Libs
        run: |
           python -m pip install --upgrade pip
           python Tools/PythonLibs/build.py Libs/Python/Common/ Libs/Python/

      # Installs module dependencies
      - name: Install dependencies
        run: |
          cd WordNet/
          pip install -r requirements.txt --find-links ./Libs/Python/
      
      # Run module unit tests    
      - name: Run tests with unittest
        run: |
          cd WordNet/tests
          python -m unittest discover
